name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install Packages
      - uses: actions/setup-node@master
        with:
          version: 10.16.2
      - run: yarn install

      - name: Unit Tests
      - run: yarn test:ci

      - name: Upload coverage to Codecov
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.codecov_token }}
