name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Node setup
        uses: actions/setup-node@master
        with:
          version: "10.16.2"

      - name: Install packages
        run: yarn install

      - name: Build apk
        run: yarn build:android
